# Generated by Django 4.0.4 on 2022-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Echipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
                ('numar_min_de_jucatori', models.IntegerField()),
                ('numar_max_de_jucatori', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('gen', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('dificultate', models.CharField(choices=[('incepator', 'Incepator'), ('intermediar', 'Intermediar'), ('avanasat', 'Avansat')], max_length=20)),
                ('jucator', models.CharField(max_length=40)),
                ('deschisa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
