# Generated by Django 4.0.4 on 2022-05-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echipa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echipa',
            old_name='description',
            new_name='descriere',
        ),
    ]
